<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\ViewsDeVentanasEmergentes\**" />
    <EmbeddedResource Remove="Views\ViewsDeVentanasEmergentes\**" />
    <None Remove="Views\ViewsDeVentanasEmergentes\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Fonts\lucida_handwriting.ttf" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Fonts\lucida_handwriting.ttf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Acr.UserDialogs" Version="7.2.0.534" />
    <PackageReference Include="MarcTron.Admob" Version="1.6.6" />
    <PackageReference Include="Rg.Plugins.Popup" Version="2.0.0.13" />
    <PackageReference Include="Xam.Plugins.Settings" Version="3.1.1" />
    <PackageReference Include="Xamarin.CommunityToolkit" Version="1.2.0" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2125" />
    <PackageReference Include="Xamarin.Essentials" Version="1.7.0" />
    <PackageReference Include="Xamarin.Forms.PancakeView" Version="2.3.0.759" />
    <PackageReference Include="Xamarin.Plugins.Clipboard" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\IURIS.BIZ\IURIS.BIZ.csproj" />
    <ProjectReference Include="..\..\IURIS.COMMON\IURIS.COMMON.csproj" />
    <ProjectReference Include="..\..\IURIS.DAL\IURIS.DAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Mono.Android">
      <HintPath>..\..\..\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v8.1\Mono.Android.dll</HintPath>
    </Reference>
    <Reference Include="System.Drawing.Common">
      <HintPath>..\..\..\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.Drawing.Common.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="PageInicioDeSesion.xaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Detail\PageMotrarCapitulosConCodigos.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Detail\ViewDetail.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="FirtsView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Master\ViewMaster.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="PageCrearCuenta.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="PageInicioDeSesion.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="PageRecuperarCuenta.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Baners\baner.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ViewsApuntes\MisApuntes.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ViewsApuntes\ViewsMisApuntes.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ViewsCargarLey\ViewCargarLey.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ViewsClasificaciones\ViewMiClasificacionPersonalizada.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ViewsClasificaciones\ViewsMisClasificaciones.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ViewsVentanasEmergentes\WindowOfComprarEspacio.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ViewsVentanasEmergentes\WindowOfEmergencyCrearNota.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ViewsVentanasEmergentes\WindowOfEmergencyNombreDeApunte.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ViewsVentanasEmergentes\WindowOfEmergencyNuevaClasificacion.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ViewsVentanasEmergentes\WindowOfMembresiaPlatino.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ViewsVentanasEmergentes\WindowOfMenuAccion.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>